# Generated by Django 4.1 on 2022-08-30 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import food.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=210)),
                ('note', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to=food.models.upload_location)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Added Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=210)),
                ('content', models.TextField()),
                ('mealsToConsume', models.TextField(max_length=5000, verbose_name='Meals to consume')),
                ('mealsToAvoid', models.TextField(max_length=5000, verbose_name='Meals to avoid')),
                ('dietTips', models.TextField(max_length=5000, verbose_name='Diet Tips')),
                ('image', models.ImageField(upload_to=food.models.upload_location)),
                ('diseaseTag', models.TextField(blank=True, max_length=200, null=True, verbose_name='disease tag')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
